config/routes.rb
Hsahara::Application.routes.draw do

  get "home/pie_chart_data", :as => :pie_chart_data

  get "home/bar_chart_data", :as => :bar_chart_data

  put "rooms/unblock_room", :as => :unblock_room

  put "rooms/block_room", :as => :block_room

  get "service_items/:id" => "service_items#get_service_item"

  delete "line_items/:id" => "line_items#delete_line_item", :as => "delete_line_item"

  put "line_items/:id" => "line_items#edit_line_item", :as => "edit_line_item"

  get "line_items/:id" => "line_items#get_line_items", :as => "line_item"

  post "service_items/add_service", :as => "add_service"

  delete "service_items/delete_service", :as => "delete_service"

  post "payments/add_payment", :as => "add_payment"

  delete "payments/delete_payment", :as => "delete_payment"

  put "checkins/shift_room", :as => "shift_room"

  devise_for :admins

  devise_for :users

  resources :services

  resources :companies

  get "home/index", :as => "user_root"

  get "home/login"

  get "home/send_report"

  put "checkins/split_room" => "checkins#split_room", :as => "split_room"

  match "/admin" => "home#admin", :as => "admin_root"

  get "/checkout/:id" => "checkins#checkout"

  resources :checkins

  resources :rooms

  resources :room_types

  resources :guests

  root :to => "home#login"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  has_many :service_items, :dependent => :destroy
  has_many :payments, :dependent => :destroy

  has_and_belongs_to_many :guests
  belongs_to :company
  belongs_to :bill_to_owner,:polymorphic => true


  def pending_balance
    total_charges - payments.sum(:amount)
  end

  def total_charges
    li_amount = 0
    line_items.each do |li|
      li_amount += li.amount
    end
    li_amount + service_items.sum(:amount)
  end

  def discount?
    line_items.each do |li|
      if li.rate < li.room.room_type.baserate
        return true
      end
    end
    return false
  end

  def extraperson?
    line_items.each do |li|
      if not li.extraperson.nil? and li.extraperson != 0
        return true
      end
    end
    return false
  end

  def can_split?
    if line_items.length < 2
      return false
    elsif line_items.length == 2 
      line_items.each do |li|
        if li.freez
          return false
        end
      end
    end
    return true
  end

  def revenue_for_day(mydate)
    total = 0
    payment = 0
    line_items.each do |li|
      if status.nil? 
        if mydate > li.fromdate.to_date and not li.freez
          total += li.amount_per_day
        elsif li.freez and li.todate.to_date > mydate
          total += li.amount_per_day      
        end
      else
        total += li.amount_per_day if li.todate.to_date > mydate and li.fromdate.to_date < mydate
      end
    end


    s = ServiceItem.arel_table
    st_time = mydate.to_time.beginning_of_day
    en_time = mydate.to_time.end_of_day


    total += service_items.select("sum(amount) as amt").where(s[:date].gteq(st_time)).where(s[:date].lteq(en_time))[0].amt.to_i

    p = Payment.arel_table
    payment += payments.select("sum(amount) as amt").where(p[:created_at].gteq(st_time)).where(p[:created_at].lteq(en_time))[0].amt.to_i


    return total,payment,line_items.length
  end


  def checkout
    line_items.each do |li|
      li.update_attribute(:todate, Time.now.in_time_zone)
      li.room.update_attribute('status',nil)
    end
    update_attribute(:status, "checked out")
    update_attribute(:todate, Time.now.in_time_zone)
  end

  def update_fromdate
    update_attribute(:fromdate,line_items.order("fromdate asc")[0].fromdate)
  end


end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :checkins
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  has_and_belongs_to_many :checkins
  validates_presence_of :FirstName
  validates_presence_of :LastName

  def name
    self.FirstName  + " " + self.LastName
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :room
  belongs_to :checkin
  after_create :block_room
  before_destroy :unblock_room

  validates_numericality_of :rate
  validates_numericality_of :extraperson
  
  def amount
    amount_per_day * no_of_days
  end
  
  def amount_per_day
    (rate  + extraperson + ((rate + extraperson) * tax/100).to_i ) 
  end


  def no_of_days
    n = 0

    if checkin.status.nil? 
      today = freez ? todate.in_time_zone(APP_CONFIG['hotel_time_zone']) : Time.now.in_time_zone(APP_CONFIG['hotel_time_zone'])
    else
      if todate == fromdate
        today = checkin.todate.in_time_zone(APP_CONFIG['hotel_time_zone'])
      else
        today = todate.in_time_zone(APP_CONFIG['hotel_time_zone']) 
      end
    end

    n = n + 1 if from.hour < APP_CONFIG['hotel_checkout_hour'] 

    n = n + 1 if today.hour > APP_CONFIG['hotel_checkout_hour'] 

    return n + (today.to_date - from.to_date).to_i
  end

  def from
    fromdate.in_time_zone(APP_CONFIG['hotel_time_zone'])
  end

  def discount
    (100 - (rate.to_f/room.room_type.baserate.to_f) * 100).round(2)
  end
  
 private
  def block_room
    room.update_attribute('status','blocked - checked in')
  end

  def unblock_room
    room.update_attribute('status',nil)
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :checkin
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_type
  has_many :line_items
  cattr_reader :per_page
  @@per_page = 12
  scope :available,{:conditions => "status is NULL"}

  def roomtype
    return number + " - " + room_type.name + " # " + room_type.baserate.to_s
  end

  def current_checkin
    Checkin.where("status is NULL").each do |c|
      c.line_items.each do |li|
        return c if not li.freez and li.room_id == id
      end
    end
    return nil
    #Checkin.where("status is NOT NULL").line_items.each 
  end

end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_items
end

app/models/service_item.rb
class ServiceItem < ActiveRecord::Base
  belongs_to :service
  belongs_to :checkin
  belongs_to :room
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_browser_check.html.haml
#browser_check_dialog{:title => "Browser not supported", :style => "display:none"}
  #browser_msg
  #browser_div
    %ul
      %li.chrome
        %a{:href => "http://www.google.com/chrome"}
          ="Google Chrome"
      %li.firefox
        %a{:href => "http://www.google.com/chrome"}
          ="Firefox 3.5+"
      %li.safari
        %a{:href => "http://www.google.com/chrome"}
          ="Apple Safari"


:javascript
  $('#browser_check_dialog').dialog({
    autoOpen: false,
    width: 500,
    height: 200,
    modal: true,
    buttons: {
      "I have been warned, let me in": function() { 
        $(this).dialog("close"); 
      } 
    }
  });

  jQuery.each(jQuery.browser, function(i) {
    if($.browser.msie){
      $('#browser_msg').html('Your browser is not supported, please view this site in following browsers:');
      $('#browser_check_dialog').dialog('open');
    }
    else if($.browser.mozilla){
      console.log($.browser.version);
      if( parseFloat($.browser.version) < parseFloat('1.9') ){
        $('#browser_msg').html('Your browser is not supported, please view this site in following browsers:');
        $('#browser_check_dialog').dialog('open');
      }
    }
  });

app/views/shared/_charts.html.haml
#piediv  
Select Date: 
=text_field_tag :occupancy_date, "#{Date.today.strftime("%Y-%m-%d")}"
#bardiv
:javascript
  drawpie();
  drawbar();
  function drawpie(dat){
    var pie_chart = new FusionCharts("/charts/FCF_Pie3D.swf", "Pie", "350", "250");
    pie_url = "/home/pie_chart_data";
    pie_chart.setDataURL(pie_url);
    pie_chart.render("piediv");
  }

  function drawbar(dat){
    var bar_chart = new FusionCharts("/charts/FCF_MSColumn3DLineDY.swf", "Bar", "450","300");
    bar_url = "/home/bar_chart_data?date=" + dat;
    bar_chart.setDataURL(bar_url);
    bar_chart.render("bardiv");
  }

  $('#occupancy_date').datepicker({ defaultDate: Date.today, dateFormat: "yy-mm-dd"});
  $('#occupancy_date').change(function() {
    drawbar($('#occupancy_date').val());
  });

app/views/shared/_checkout_table.html.haml
.checkout
  %ul
    %li 
      %b Bill to:
    -if @checkin.company_id == 1
      - if @checkin.guests.length < 2
        %li= @checkin.guests[0].name
      - else
        %li= select_tag :bill_to, options_for_select(@checkin.guests.collect{|g| g.name})
    -else
      %li= select_tag :bill_to, options_for_select(@checkin.guests.collect{|g| [g.name, "Guest-#{g.id}"]}.unshift([@checkin.company.name, "Company-#{@checkin.company.id}"]))
  #line_items
    -@tamount = 0
    =render :partial => "shared/line_items"


  %hr   
  #othercharges
    =render :partial => "shared/other_charges"
  %hr      
  #payments
    =render :partial => "shared/payments"
  %hr
  #totaldiv
    =render :partial => "shared/totaldiv"




  

app/views/shared/_header.html.haml
#header
  %h1
    =APP_CONFIG['hotel_name']
  %ul
    %li{:class => "home #{current_page?(user_root_url)?'current':''}"}
      =link_to user_root_url do
        %span Home
    %li{:class => "checkin #{current_page?(new_checkin_url)?'current':''}"}
      =link_to new_checkin_url do
        %span New Checkin
    %li.admin
      =link_to admin_root_url do
        %span Admin
    - if user_signed_in?
      %li.logout
        =link_to destroy_user_session_path do
          %span Logout

#spacer
.clear

app/views/shared/_line_items.html.haml
%hr
%h4 Room Charges
%table
  %tr
    %th
    %th Room
    %th Rate
    %th Discount
    %th Applied Rate
    %th Extra Person
    %th Tax
    %th Total Per Day
    %th No of Days
    %th Amount
    - @checkin.line_items.each do |li|
      %tr{:class => "#{ "freezed" if li.freez}"}
        %td
          =link_to "#",:class => "li-details", :rel => "/line_items/#{li.id}", :title => "Room checkin details" do
            %span{:class => "ui-icon ui-icon-info"}
        %td
          -if @checkin.can_split?
            %a{:href => "#", :id => "split-#{li.id}", :class => "splitlink"}
              = li.room.number 
              %span{"class" => "ui-icon ui-icon-extlink", :style => "margin-right:0px;float:right;"}
          -else
            =li.room.number
        %td= li.room.room_type.baserate
        %td= li.discount.to_s + "%"
        %td= li.rate
        %td= li.extraperson
        %td= li.tax.to_s + "%"
        %td= li.amount_per_day.to_s
        %td= li.no_of_days.to_s
        %td= li.amount
        -@tamount += li.amount
      
  %tr
    %th{:colspan => 9} Total Rooms Charges
    %td.charges= @tamount

app/views/shared/_notice.html.haml
.ui-widget
  -if flash[:notice]
    .ui-state-highlight.ui-corner-all{:style => "padding: 0 .7em;"}
      %span{:class => "ui-icon ui-icon-info" , :style => "float: left; margin-right: .3em;"}
      = flash[:notice]
      %a{:href => "#", :class => "close_alert"}
        %span{:class => "ui-icon ui-icon-close", :style => "float:left;margin-top:3px;"}
        close
  -if flash[:alert]
    .ui-state-error.ui-corner-all{:style => "padding: 0 .7em;"}
      %span{:class => "ui-icon ui-icon-alert" , :style => "float: left; margin-right: .3em;"}
      = flash[:alert]
      %a{:href => "#", :class => "close_alert"}
        %span{:class => "ui-icon ui-icon-close", :style => "float:left;margin-top:3px;"}
        close

:javascript
  $('.close_alert').click(function () {
    $(this).parent().slideUp('slow');
    return false;
  });
:css
  .close_alert{
    float:right;
    width:80px;
  }

app/views/shared/_other_charges.html.haml
%h4 
  Other Charges
%ul
  %li
    =link_to "+ add","#",:class => "add_service", :id => "serviceitemcheckinid-#{@checkin.id}"
%table{:style => "float:right"}
  %tr
    %th
    %th
    %th Date
    %th Type
    %th Room
    %th Amount
  - @checkin.service_items.each do |si|
    %tr{:id => "srow-#{si.id}"}
      %td 
        %a{:href => "#", :class => "delete_service"}
          %span{:class => "ui-icon ui-icon-close"}
      %td
        =link_to "#",:class => "li-details", :rel => "/service_items/#{si.id}", :title => "Other Charges details" do
          %span{:class => "ui-icon ui-icon-info"}

      %td= si.created_at.strftime("%Y/%m/%d")
      %td= si.service.name
      %td= si.room.number if not si.room.nil?
      %td= si.amount

  %tr
    %th{:scope => "row", :colspan => 5} Total Other Charges
    %td.charges= @checkin.service_items.sum(:amount)

app/views/shared/_payments.html.haml
%h4 
  Payments
%ul
  %li
    =link_to "+ add","#",:class => "add_payment",:id => "paymentcheckinid-#{@checkin.id}"
%table{:style => "float:right"}
  %tr
    %th
    %th Date
    %th Description
    %th Amount
  -@checkin.payments.each do |p|
    %tr{:id => "prow-#{p.id}"}
      %td 
        %a{:href => "#", :class => "delete_payment"}
          %span{:class => "ui-icon ui-icon-close"}

      %td= p.created_at.strftime("%Y/%m/%d")
      %td= p.description
      %td= p.amount
  %tr
    %th{:scope => "row",:colspan => 3} Total Payments
    %td.payment= @checkin.payments.sum(:amount)

app/views/shared/_roomtable.html.haml
%table.roomlist{:cellspacing => 0, :style => "width: 100%"}
  - @rooms.each do |room|
    - unless room.status.nil?
      - if room.status.match(/check/)
        - checkin = @room_checkin[room]
        
    %tr.block{:id => "#{checkin.nil? ? '' : 'room-' + room.id.to_s  + '-checkin-' + checkin.id.to_s}"}
      %th{:scope => 'row'}= room.number
      %td
        -if checkin
          .gb
            %div{:class => "#{checkin.nil? ? 'guestbox' : 'guestbox checkedin'}"}
              .name="#{checkin.guests[0].FirstName} #{checkin.guests[0].LastName}"
          %ul.roomfunctions
            %li
              =link_to "Shift Room","#",:class => "shiftroom_link"
        -elsif not room.status.nil?
          %ul.general
            - if room.status.match(/maintenance/i)
              %li
                =image_tag "maintenance.png"
              %li.text
                %b Under Maintenance
            - elsif room.status.match(/occupied/i)
              %li
                =image_tag "staff.png"
              %li.text
                %b Occupied by Staff
          %ul.roomfunctions  
            %li
              =link_to "Unblock Room", "#", :class => "unblockroom_link", :id => "unblock-#{room.id}"
        -else
          .gb
          %ul.roomfunctions
            %li
              =link_to "Block Room","#",:class => :blockroom_link, :id => "block-#{room.id}"

app/views/shared/_totaldiv.html.haml
%button checkout
=link_to_function "View Print", "window.open('/checkout/#{@checkin.id.to_s}','Check Out', 'height=400,width=400');"

%table{:style => "float:right"}
  %tr
    %th{:scope => "row"} Total Charges
    %td.charges= @tamount + @checkin.service_items.sum(:amount)
  %tr
    %th{:scope => "row"} Total Payments
    %td.payment= @checkin.payments.sum(:amount)
  %tr
    %th{:scope => "row"} Total Pending
    %td.pending= @tamount + @checkin.service_items.sum(:amount) - @checkin.payments.sum(:amount)