config/routes.rb
Hsahara::Application.routes.draw do

  get "home/pie_chart_data", :as => :pie_chart_data

  get "home/bar_chart_data", :as => :bar_chart_data

  put "rooms/unblock_room", :as => :unblock_room

  put "rooms/block_room", :as => :block_room

  get "service_items/:id" => "service_items#get_service_item"

  delete "line_items/:id" => "line_items#delete_line_item", :as => "delete_line_item"

  put "line_items/:id" => "line_items#edit_line_item", :as => "edit_line_item"

  get "line_items/:id" => "line_items#get_line_items", :as => "line_item"

  post "service_items/add_service", :as => "add_service"

  delete "service_items/delete_service", :as => "delete_service"

  post "payments/add_payment", :as => "add_payment"

  delete "payments/delete_payment", :as => "delete_payment"

  put "checkins/shift_room", :as => "shift_room"

  devise_for :admins

  devise_for :users

  resources :services

  resources :companies

  get "home/index", :as => "user_root"

  get "home/login"

  get "home/send_report"

  put "checkins/split_room" => "checkins#split_room", :as => "split_room"

  match "/admin" => "home#admin", :as => "admin_root"

  get "/checkout/:id" => "checkins#checkout"

  resources :checkins

  resources :rooms

  resources :room_types

  resources :guests

  root :to => "home#login"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => ['index']
  before_filter :authenticate_admin!,:only => ['admin']

  def index
    @rooms = Room.paginate :page => params[:page],:order => "id"
    @rooms_available = Room.available
    @room_checkin = Hash.new
    Checkin.where("status is NULL").each do |c|
      c.line_items.each do |li|
        if not li.freez 
          @room_checkin[li.room] = c
        end
      end
    end

  end

  def login

    respond_to do |format|
      format.html { 
        if user_signed_in?
          redirect_to user_root_path
        else
          render :layout => "user" 
        end
      }
    end
    
  end

  def send_report
    ct = Checkin.arel
    @checkins = Checkin.where(ct["created_at"].gteq(Date.today - 1.day)).or(ct["status"].eq(nil))
    ReportMailer.daily_report(@checkins).deliver
    render :text => "ok"
  end

  def pie_chart_data
    @o_rooms = Room.where("status is NOT NULL and status like '%check%'").length
    @un_rooms = Room.where("status is NULL").length
    @m_rooms = Room.all.length - @o_rooms - @un_rooms
  end

  def bar_chart_data
    ct = Checkin.arel_table
    startdate = Date.new
    e = Date.new
    if params[:date] and params[:date] != "undefined" and (Date.parse(params[:date]).beginning_of_week() - 1.day < Time.now.beginning_of_week().to_date)
      startdate = Date.parse(params[:date]).beginning_of_week()
      enddate = Date.parse(params[:date]).end_of_week()
      @checkins = Checkin.where(ct[:fromdate].gteq(startdate)).where(ct[:todate].lteq(enddate))
      @checkins.concat Checkin.where(ct[:fromdate].gteq(startdate)).where(ct[:status].eq(nil))
      e = enddate
    else
      startdate =  Time.now.beginning_of_week().to_date
      @checkins = Checkin.where(ct[:fromdate].gteq(startdate - 1.day).or(ct[:status].eq(nil)))
      e = Date.today
    end
    #@date_revenue = Hash.new
    @date_revenue = ActiveSupport::OrderedHash.new
    t = startdate
    while t <= e
      @date_revenue[t.to_time.strftime("%d/%m")] = Array.new
      @date_revenue[t.to_time.strftime("%d/%m")][0] = 0
      @date_revenue[t.to_time.strftime("%d/%m")][1] = 0
      @date_revenue[t.to_time.strftime("%d/%m")][2] = 0
      @checkins.each do |c|
        arr = c.revenue_for_day(t)
        @date_revenue[t.to_time.strftime("%d/%m")][0] += arr[0]
        @date_revenue[t.to_time.strftime("%d/%m")][1] += arr[1]
        @date_revenue[t.to_time.strftime("%d/%m")][2] += arr[2]
      end
      t = t + 1.day
    end

  end

  
  def admin


  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_intro.html.haml
#mlogo
  %h1 One Hill Motel


#accordion
 
  %h3
    %a{:href => "#"} Assumed Workflow
  %div 
    %ul
      %li
        after login, the desk clerk would be able to see current checkins, todays revunue(work in progress), upcoming reservations(work in progress) on a single screen.
      %li
        desk clerk can make checkin, using ~ new checkin. every checkin is a group checkin by default, so rooms/guests/company can be added as needed. 
  %h3
    %a{:href => "#"} Features
  %div 
    %ul
      %li
        easy and intutive checkin interface
      %li
        customize services, add payments 
      %li
        split group checkins any time into individual checkins
      %li
        room shift/upgrade/downgrade (coming soon)
      %li
        reservation feature (coming soon)

  

  

app/views/home/admin.html.haml
.block-border
  .block-content
    - if admin_signed_in?
      .right
        =link_to destroy_admin_session_path do
          %span Logout

    %h3 Welcome Admin
    %p You can add/modify Room/Room Types
    %br
    %br
    =link_to rooms_path do
      %h2 Rooms
    %br
    %hr
    =link_to room_types_path do
      %h2 Room Types
    %br
    %hr
    =link_to services_path do
      %h2 Room Services
    %br
    %hr
    =link_to services_path do
      %h2 Add User

app/views/home/index.html.haml
.block-border
  .block-content{:style => "overflow:auto;padding-top:5px;background:#aaa;"}
    .block-controls
      =will_paginate @rooms 
    #panel-frame{:style => "width:49%"}
      .panel
        .head
          %a{:href=> "#",:class => "close"} close
        .data
    .left.no-margin{:style => "width:51%"}
      =render :partial => "shared/roomtable"

    .right{:style => "width:50%;"}
      %h3 Welcome to Hotel Management Home Page
      %hr
      =render :partial => "shared/charts"
     


#service_dialog{ :title => "Add Service",:style => "display:none"}
  =render :partial => "service_items/service_item_form"

#payment_dialog{:title => "Add Payments", :style => "display:none"}
  =render :partial => "payments/payment_form"

#checkout_dialog{:title => "Checkout", :style => "display:none;"}
  #pending_amount_div
  #checkout_form_div

#splitroom_dialog{:title => "Split Room as New Checkin", :style => "display:none;"}
  Do you want to split Room -
  %span{:id => "split_room_number"}
  into separate checkin?
  =form_tag split_room_url,:id => :splitroom_form, :method => :put do
    =hidden_field_tag :splitroom_line_item_id

#delete_room_service_dialog{:title => "Delete Room Service", :style => "display:none;"}
  Do you want to delete Room Service
  %span{:id => "delete_room_service"}
  Item?
  =form_tag delete_service_url, :id => "delete_service_form", :method => :delete, :remote => true do
    =hidden_field_tag "delete_service_item_id"

#delete_payment_dialog{:title => "Delete Payment", :style => "display:none;"}
  Do you want to delete Payment
  %span{:id => "delete_payment"}
  Item?
  =form_tag delete_payment_url, :id => "delete_payment_form", :method => :delete, :remote => true do
    =hidden_field_tag "delete_payment_id"

#shiftroom_dialog{:title => "Shift Room",:style => "display:none"}
  =form_tag shift_room_url, :id => :shiftroom_form, :method => :put do
    =hidden_field_tag :shiftroom_room_id_checkin_id
    =label_tag "Shift to:"
    =select_tag :shift_room_id, options_from_collection_for_select(@rooms_available,:id,:roomtype)
    %br
    =label_tag "Rate"
    =text_field_tag :rate
    %br
    =label_tag "tax"
    =text_field_tag :tax
    \%
#edit_line_item_dialog{:title => "Edit Checkin",:style => "display:none"}
  #line_item_form

#block_room_dialog{:title => "Block Room?",:style => "display:none"}
  Do you want to block Room -
  %span{:id => "block_room_number"}
  &nbsp;?
  =form_tag block_room_url,:id => :block_room_form, :method => :put do
    =label_tag "Specify Reason"
    =select_tag "reason",options_for_select(["Maintenance","Occupied by Staff"])
    =hidden_field_tag :block_room_id
#unblock_room_dialog{:title => "Unblock Room?",:style => "display:none"}
  Do you want to unblock Room -
  %span{:id => "unblock_room_number"}
  &nbsp;?
  =form_tag unblock_room_url,:id => :unblock_room_form, :method => :put do
    =hidden_field_tag :unblock_room_id


:javascript
  $('#service_form').bind("ajax:loading",  function(){
    $('.add_service').after('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });
  $('#payment_form').bind("ajax:loading",  function(){
    $('.add_payment').after('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });
  $('#delete_service_form').bind("ajax:loading",  function(){
    $('.add_service').after('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });
  $('#edit_line_item_form').bind("ajax:loading",  function(){
    $('#line_items').html('<div id="loading"><img style = "float:right;margin:3px;" src="/images/smallloading.gif"/></div>')
  });

  $(document).ready(function() {

    $('.shiftroom_link').click(function(){
      $('#shiftroom_dialog').dialog('open');
      $('#shiftroom_room_id_checkin_id').val($(this).parents('tr').attr('id'));
      return false;
     });

    $('.blockroom_link').click(function(){
      $('#block_room_dialog').dialog('open');
      $('#block_room_id').val($(this).attr('id').split('-')[1]);
      $('#block_room_number').html($(this).parents('.block').find('th[scope=row]').text());
      return false;
     });

    $('.unblockroom_link').click(function(){
      $('#unblock_room_dialog').dialog('open');
      $('#unblock_room_id').val($(this).attr('id').split('-')[1]);
      $('#unblock_room_number').html($(this).parents('.block').find('th[scope=row]').text());
      return false;
     });

    $('.checkedin').click(function(){

      var id= $(this).parents('tr').attr('id');
      myarr = id.split('-');
      $('#service_item_room_id').val(myarr[1]);
      var data_id= $(".data").attr('id');
      if(data_id == ''){
        $('.data').attr('id','data' + id);
      }
      var panel= $('.panel');
      var panel_width=$('.panel').css('left');

      if(data_id == 'data' + id){
        panel.animate({left: parseInt(panel.css('left'),0) == 0 ? +panel.outerWidth() : 0});
      }
      else{
        $('.data').attr('id','data' + id);
        if(panel_width =='465px'){

        }
        else{
          panel.animate({left: parseInt(panel.css('left'),0) == 0 ? +panel.outerWidth() : 0});
        }
        $.ajax({
          beforeSend: function(){$('.data').html('<div style="margin:100px";><img src="/images/smallloading.gif"/>&nbsp;<b>Loading..</b></div>');},
          url: '/checkins/' + myarr[3]
        });
      }
      return false;
    });

    $('.close').click(function(){
      var panel= $('.panel');
      panel.animate({left: parseInt(panel.css('left'),0) == 0 ? +panel.outerWidth() : 0});
      return false;
    });
  });
     
  
  $('#checkout_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#checkout_dialog form').submit();
        window.open('/checkout/' + $('#service_item_checkin_id').val(),'Check Out', 'height=400,width=400');
        window.location="/home/index";
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#service_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#service_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#payment_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#payment_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });

  $('#splitroom_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Yes": function() { 
        $(this).dialog("close"); 
        $('#splitroom_form').submit();
      }, 
      "No": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#delete_room_service_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Yes": function() { 
        $(this).dialog("close"); 
        $('#delete_service_form').submit();
      }, 
      "No": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#shiftroom_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Shift": function() { 
        $(this).dialog("close"); 
        $('#shiftroom_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });

  $('#delete_payment_dialog').dialog({
    autoOpen: false,
    width: 400,
    buttons: {
      "Yes": function() { 
        $(this).dialog("close"); 
        $('#delete_payment_form').submit();
      }, 
      "No": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#edit_line_item_dialog').dialog({
    autoOpen: false,
    width: 450,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#edit_line_item_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#block_room_dialog').dialog({
    autoOpen: false,
    width: 450,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#block_room_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });
  $('#unblock_room_dialog').dialog({
    autoOpen: false,
    width: 450,
    buttons: {
      "Save": function() { 
        $(this).dialog("close"); 
        $('#unblock_room_form').submit();
      }, 
      "Cancel": function() { 
        $(this).dialog("close"); 
      } 
    }
  });

app/views/home/login.html.haml
%h2 Sign In
%i Login using info@onehillmotel.com password : 123456
= form_for("user", :url =>  user_session_path) do |f|
  %p
    = f.label :email
    %br
    = text_field_tag 'user[email]'
  %p
    = f.label :password
    = password_field_tag 'user[password]'
  %p
    = f.check_box :remember_me
    = f.label :remember_me
  = f.submit "Sign in"

app/views/home/rooms.js.erb
#tablediv.html(escape_javascript('<%= render :partial => "shared/roomtable" %>'));