config/routes.rb
Hsahara::Application.routes.draw do

  get "home/pie_chart_data", :as => :pie_chart_data

  get "home/bar_chart_data", :as => :bar_chart_data

  put "rooms/unblock_room", :as => :unblock_room

  put "rooms/block_room", :as => :block_room

  get "service_items/:id" => "service_items#get_service_item"

  delete "line_items/:id" => "line_items#delete_line_item", :as => "delete_line_item"

  put "line_items/:id" => "line_items#edit_line_item", :as => "edit_line_item"

  get "line_items/:id" => "line_items#get_line_items", :as => "line_item"

  post "service_items/add_service", :as => "add_service"

  delete "service_items/delete_service", :as => "delete_service"

  post "payments/add_payment", :as => "add_payment"

  delete "payments/delete_payment", :as => "delete_payment"

  put "checkins/shift_room", :as => "shift_room"

  devise_for :admins

  devise_for :users

  resources :services

  resources :companies

  get "home/index", :as => "user_root"

  get "home/login"

  get "home/send_report"

  put "checkins/split_room" => "checkins#split_room", :as => "split_room"

  match "/admin" => "home#admin", :as => "admin_root"

  get "/checkout/:id" => "checkins#checkout"

  resources :checkins

  resources :rooms

  resources :room_types

  resources :guests

  root :to => "home#login"

end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  before_filter :authenticate_admin!
  # GET /room_types
  # GET /room_types.xml
  def index
    @room_types = RoomType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @room_types }
    end
  end

  # GET /room_types/1
  # GET /room_types/1.xml
  def show
    @room_type = RoomType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @room_type }
    end
  end

  # GET /room_types/new
  # GET /room_types/new.xml
  def new
    @room_type = RoomType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @room_type }
    end
  end

  # GET /room_types/1/edit
  def edit
    @room_type = RoomType.find(params[:id])
  end

  # POST /room_types
  # POST /room_types.xml
  def create
    @room_type = RoomType.new(params[:room_type])

    respond_to do |format|
      if @room_type.save
        format.html { redirect_to(@room_type, :notice => 'Room type was successfully created.') }
        format.xml  { render :xml => @room_type, :status => :created, :location => @room_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @room_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /room_types/1
  # PUT /room_types/1.xml
  def update
    @room_type = RoomType.find(params[:id])

    respond_to do |format|
      if @room_type.update_attributes(params[:room_type])
        format.html { redirect_to(@room_type, :notice => 'Room type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @room_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /room_types/1
  # DELETE /room_types/1.xml
  def destroy
    @room_type = RoomType.find(params[:id])
    @room_type.destroy

    respond_to do |format|
      format.html { redirect_to(room_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/room_types/_form.html.erb
<%= form_for(@room_type) do |f| %>
  <% if @room_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

      <ul>
      <% @room_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :baserate %><br />
    <%= f.text_field :baserate %>
  </div>

  <div class="field">
    <%= f.label :facilities %><br />
    <%= f.text_area :facilities %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_types/edit.html.erb
<h1>Editing room_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @room_type %> |
<%= link_to 'Back', room_types_path %>

app/views/room_types/index.html.erb
<h1>Listing room_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Base Rate</th>
    <th>Facilities</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @room_types.each do |room_type| %>
  <tr>
    <td><%= room_type.name %></td>
    <td><%= room_type.baserate if not room_type.baserate.nil? %></td>
    <td><%= room_type.facilities %></td>
    <td><%= link_to 'Show', room_type %></td>
    <td><%= link_to 'Edit', edit_room_type_path(room_type) %></td>
    <td><%= link_to 'Destroy', room_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room type', new_room_type_path %>

app/views/room_types/new.html.erb
<h1>New room_type</h1>

<%= render 'form' %>

<%= link_to 'Back', room_types_path %>

app/views/room_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @room_type.name %>
</p>

<p>
  <b>Facilities:</b>
  <%= @room_type.facilities %>
</p>


<%= link_to 'Edit', edit_room_type_path(@room_type) %> |
<%= link_to 'Back', room_types_path %>