config/routes.rb
Hsahara::Application.routes.draw do

  get "home/pie_chart_data", :as => :pie_chart_data

  get "home/bar_chart_data", :as => :bar_chart_data

  put "rooms/unblock_room", :as => :unblock_room

  put "rooms/block_room", :as => :block_room

  get "service_items/:id" => "service_items#get_service_item"

  delete "line_items/:id" => "line_items#delete_line_item", :as => "delete_line_item"

  put "line_items/:id" => "line_items#edit_line_item", :as => "edit_line_item"

  get "line_items/:id" => "line_items#get_line_items", :as => "line_item"

  post "service_items/add_service", :as => "add_service"

  delete "service_items/delete_service", :as => "delete_service"

  post "payments/add_payment", :as => "add_payment"

  delete "payments/delete_payment", :as => "delete_payment"

  put "checkins/shift_room", :as => "shift_room"

  devise_for :admins

  devise_for :users

  resources :services

  resources :companies

  get "home/index", :as => "user_root"

  get "home/login"

  get "home/send_report"

  put "checkins/split_room" => "checkins#split_room", :as => "split_room"

  match "/admin" => "home#admin", :as => "admin_root"

  get "/checkout/:id" => "checkins#checkout"

  resources :checkins

  resources :rooms

  resources :room_types

  resources :guests

  root :to => "home#login"

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :checkins
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.xml
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.js
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :inchargeperson %><br />
    <%= f.text_field :inchargeperson %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :creditlimit %><br />
    <%= f.text_field :creditlimit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/create.js.erb
$('#company option:last').before($('<option></option>').val('<%= @company.id %>').text('<%= @company.name %>'));
$('#company').val('<%= @company.id %>');
$('#loading').remove();

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Inchargeperson</th>
    <th>Address</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Creditlimit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.inchargeperson %></td>
    <td><%= company.address %></td>
    <td><%= company.email %></td>
    <td><%= company.phone %></td>
    <td><%= company.creditlimit %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Inchargeperson:</b>
  <%= @company.inchargeperson %>
</p>

<p>
  <b>Address:</b>
  <%= @company.address %>
</p>

<p>
  <b>Email:</b>
  <%= @company.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @company.phone %>
</p>

<p>
  <b>Creditlimit:</b>
  <%= @company.creditlimit %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>